### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by R2-t** [pololu/lsm6-arduino#5]
Hey there, I will use this library for a thesis project and I would like to know if this library is completely functional, because I saw some PRs without any response and they are pretty old.

Any response or explanation about how to implement it would be great. 

Thanks

**Comment by kevin-pololu** [comment]
Yes, we still support this library and try to make sure it works on the most common Arduino-compatible boards.

**Comment by PowerBroker2** [comment]
@kevin-pololu What about the old PRs?
